name: Deployement

on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        #gituser: ${{ secrets.GIT_USER }}
        #token: ${{ secrets.GIT_TOKEN }}
        script: |
          cd /opt/main/CICD
          echo ${{ secrets.PASSWORD }} | sudo -S git pull origin master
          echo ${{ secrets.PASSWORD }} | sudo -S chmod +x /opt/main/CICD/codeupdate.sh
          echo ${{ secrets.PASSWORD }} | sudo -S /opt/main/CICD/codeupdate.sh

    
